version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es01
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch2
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9200}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9300}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/logs
    depends_on:
      - elasticsearch2

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch2}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_EASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es02
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9201}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9301}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/log

  public_db:
    image: postgres:13.3
    ports:
      - 5432:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/public_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/public_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PUBLIC_DB_USER}
      POSTGRES_PASSWORD: ${PUBLIC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${PUBLIC_DB_INITDB_ARGS}
      POSTGRES_DB: ${PUBLIC_DB}

  repos_db:
    image: postgres:13.3
    ports:
      - 5433:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/repos_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/repos_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${REPOS_DB_USER}
      POSTGRES_PASSWORD: ${REPOS_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${REPOS_DB_INITDB_ARGS}
      POSTGRES_DB: ${REPOS_DB}

  batch:
    image: ddbj-batch/boot:0.0.1
    depends_on:
      - public_db
      - elasticsearch
      - elasticsearch2
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/batch:/batch
    environment:
      JAR_TARGET: ddbj-0.0.1-SNAPSHOT.jar
      ES_HOST: elasticsearch
      ES_PORT: 9200
      TARGET_DB: ${TARGET_DB}
    build:
      context: ${PWD}/batch

  api:
    image: openjdk:11-slim
    depends_on:
      - public_db
    ports:
      - "8080:8080"
      - "5050:5050"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/entrypoint.api.sh:/usr/local/bin/entrypoint.api.sh
      - ${PWD}/api:/api
      - ${PWD}/data/file:/data
    command: ["bash", "/usr/local/bin/entrypoint.api.sh"]
    restart: always
    environment:
      ENV: ${ENV}

  front:
    image: node:12.12.0
    ports:
      - "3000:3000"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - "./front:/front"
    working_dir: /front
    command: [sh, -c, yarn install;yarn run dev]
    restart: always

  ftpd:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    #    user: ${UID:-0}:${GID:-0}
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - ./data/ftp/data:/home/${FTP_USER_NAME}
      - ./data/ftp/passwd:/etc/pure-ftpd/passwd
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: /home/${FTP_USER_NAME}
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"

networks:
  default:
    name: ddbj_ld
