version: '3.5'
services:
  elasticsearch_stage:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch_stage}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms30g -Xmx30g"
      path.data: /usr/share/elasticsearch/data
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es01
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch2_stage
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9202}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9302}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/es:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/logs
    depends_on:
      - elasticsearch2_stage
    restart: always

  elasticsearch2_stage:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch2_stage}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms30g -Xmx30g"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es02
      path.data: /usr/share/elasticsearch/data
      node.max_local_storage_nodes: 2
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch_stage
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9203}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9303}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/es:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/log
    restart: always

  public_db_stage:
    image: postgres:12.0
    container_name: ${DDBJLD_POSTGRESQL_CONTAINER_NAME:-ddbjld_public_db_stage}
    ports:
      - 15432:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/public_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/psql/:/var/lib/public_db/data
    environment:
      POSTGRES_USER: ${PUBLIC_DB_USER}
      POSTGRES_PASSWORD: ${PUBLIC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${PUBLIC_DB_INITDB_ARGS}
      POSTGRES_DB: ${PUBLIC_DB}
    restart: always

  jvar_db_stage:
    image: postgres:12.0
    ports:
      - 15433:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/jvar_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/jvar_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${JVAR_DB_USER}
      POSTGRES_PASSWORD: ${JVAR_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${JVAR_DB_INITDB_ARGS}
      POSTGRES_DB: ${JVAR_DB}
    restart: always

  batch_stage:
    build:
      context: ${PWD}/batch
    image: ddbj-batch/boot:0.0.1
    depends_on:
      - public_db_stage
      - elasticsearch_stage
      - elasticsearch2_stage
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/batch:/batch
      - /gpfs1/dpl0/ddbjshare/private/ddbj.nig.ac.jp/jga/metadata:/data/jga
    environment:
      ES_HOST: elasticsearch_stage
      ES_PORT: 9200
      TARGET_DB: ${TARGET_DB}

  api_stage:
    image: openjdk:11-slim
    depends_on:
      - public_db_stage
    ports:
      - "8092:8080"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/entrypoint.api.sh:/usr/local/bin/entrypoint.api.sh
      - ${PWD}/api:/api
      - ${PWD}/data/file:/data
    command: ["bash", "/usr/local/bin/entrypoint.api.sh"]
    restart: always
    environment:
      ENV: ${ENV}
    extra_hosts:
      - "gw1:172.19.18.250"

  front_stage:
    image: node:12.12.0
    volumes:
      - "./front:/front"
    ports:
      - "3001:3000"
    user: ${UID:-0}:${GID:-0}
    working_dir: /front
    command: [sh, -c, yarn install;yarn build;yarn run start]
    restart: always

networks:
  default:
<<<<<<< HEAD
    name: ddbj_ld_stage
=======
<<<<<<< HEAD
    name: ddbj_ld_stage
=======
    name: ddbj_ld_stage
>>>>>>> c0b2b5bc3cee7522821f9227b7a0f8fc84c17746
>>>>>>> 966dded443be9420ece6b20e6e7c5f709e888a99
