version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es01
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch2
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - ddbj_ld
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9200}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9300}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/logs
    depends_on:
      - elasticsearch2

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch2}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es02
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - ddbj_ld
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9201}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9301}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/log

  public_db:
    image: postgres:12.0
    networks:
      - ddbj_ld
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/config/public_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/public_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PUBLIC_DB_USER}
      POSTGRES_PASSWORD: ${PUBLIC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${PUBLIC_DB_INITDB_ARGS}
      POSTGRES_DB: ${PUBLIC_DB}
      hostname: ${PUBLIC_DB_HOSTNAME}
      restart: always
      user: ${PUBLIC_DB_USER}

  jvar_db:
    image: postgres:12.0
    networks:
      - ddbj_ld
    ports:
      - 5433:5432
    volumes:
      - ${PWD}/config/jvar_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/jvar_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${JVAR_DB_USER}
      POSTGRES_PASSWORD: ${JVAR_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${JVAR_DB_INITDB_ARGS}
      POSTGRES_DB: ${JVAR_DB}
      hostname: ${JVAR_DB_HOSTNAME}
      restart: always
      user: ${JVAR_DB_USER}

  openam:
    build: ./config/openam
    ports:
      - "8082:8080"
    volumes:
      - ./data/openam/home:/home/openam/
      - /dev/urandom:/dev/random
      - ./data/openam/config:/usr/openam/config
    environment:
      - CATALINA_OPTS="-Xmx2048m"
    depends_on:
      - opendj
    networks:
      - ddbj_ld

  opendj:
    image: openidentityplatform/opendj:4.4.6
    ports:
      - "1389:1389"
    volumes:
      - ./config/entrypoint.opendj.sh:/opt/opendj/entrypoint.opendj.sh
      - ./data/opendj/db:/opt/opendj/db
      - ./data/opendj/config:/opt/opendj/config
      - ./data/opendj/locks:/opt/opendj/locks
      - ./config/opendj/99-user.ldif:/opt/opendj/99-user.ldif
    environment:
      OPENDJ_PASS: $OPENDJ_PASS
    entrypoint: /opt/opendj/entrypoint.opendj.sh
    networks:
      - ddbj_ld

  batch:
    image: ddbj-batch/boot:0.0.1
    depends_on:
      - public_db
      - elasticsearch
      - elasticsearch2
    volumes:
      - ${PWD}/batch:/batch
    environment:
      JAR_TARGET: ddbj-0.0.1-SNAPSHOT.jar
      ES_HOST: elasticsearch
      ES_PORT: 9200
      TARGET_DB: ${TARGET_DB}
    build:
      context: ${PWD}/batch
    networks:
      - ddbj_ld

  api:
    image: openjdk:11-slim
    depends_on:
      - public_db
    ports:
      - "8080:8080"
      - "5050:5050"
    volumes:
      - ${PWD}/config/entrypoint.api.sh:/usr/local/bin/entrypoint.api.sh
      - ${PWD}/api:/api
      - ${PWD}/data/file:/data
    command: ["bash", "/usr/local/bin/entrypoint.api.sh"]
    restart: always
    environment:
      ENV: ${ENV}
    networks:
      - ddbj_ld

  front:
    image: node:12.12.0
    volumes:
      - "./front:/front"
    working_dir: /front
    command: [sh, -c, yarn install;yarn run dev]
    ports:
      - "3000:3000"
    networks:
      - ddbj_ld

networks:
  ddbj_ld:
    external: true
