version: "3.5"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: ddbjld_elasticsearch-dev
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ddbjld_elasticsearch_passwd
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.sh"]
    volumes:
      - ${PWD}/docker/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/docker/elasticsearch/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${PERSISTENCE_DIR}/elasticsearch:/usr/share/elasticsearch/data
      - ${LOG_DIR}/elasticsearch:/usr/share/elasticsearch/logs
    restart: unless-stopped

  public_db:
    image: postgres:13.3
    container_name: ddbjld_public_db-dev
    ports:
      - "127.0.0.1:5432:5432"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/docker/public_db/init:/docker-entrypoint-initdb.d
      - ${PERSISTENCE_DIR}/public_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PUBLIC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: public_db
    restart: unless-stopped

  repos_db:
    image: postgres:13.3
    container_name: ddbjld_repos_db-dev
    ports:
      - "127.0.0.1:5433:5432"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/docker/repos_db/init:/docker-entrypoint-initdb.d
      - ${PERSISTENCE_DIR}/repos_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${REPOS_DB_USER}
      POSTGRES_PASSWORD: ${REPOS_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: repos_db
    restart: unless-stopped

  batch:
    image: ddbj-batch/boot:0.0.1
    build:
      context: ${PWD}/docker/batch
    depends_on:
      - public_db
      - elasticsearch
      - elasticsearch2
    ports:
      - "15005:5005"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/docker/batch/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${PWD}/batch:/batch
      - ${DATA_DIR}:/data_dir
    command: ["bash", "/usr/local/bin/entrypoint.sh"]
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
      ACTION: ${ACTION}
      DATE: ${DATE}
      ENV: ${ENV}

  api:
    image: ddbj-api/boot:0.0.1
    build:
      context: ${PWD}/docker/api
    depends_on:
      - public_db
      - repos_db
      - elasticsearch
      - elasticsearch2
    ports:
      - "8080:8080"
      - "5005:5005"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/docker/api/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${PWD}/api:/api
      - ${PERSISTENCE_DIR}/file:/data
    command: ["bash", "/usr/local/bin/entrypoint.sh"]
    restart: always
    environment:
      ENV: ${ENV}

  front:
    image: ddbj-sc-idp-front-dev:1
    build:
      context: .
      dockerfile: ./docker/front/development/Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: [sh, -c, yarn install;yarn run dev]
    restart: always
    networks:
      default:
        ipv4_address: 192.168.1.2

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "443:443"
      - "80:80"
    environment:
      STAGE: local
      DOMAINS: >-
        ld.test -> http://front:3000
    volumes:
      - ${PWD}/data/https-portal:/var/lib/https-portal
    networks:
      default:
        ipv4_address: 192.168.1.3

  ftpd:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
    volumes:
      - ./data/ftp/data:/home/${FTP_USER_NAME}
      - ./data/ftp/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${FTP_USER_NAME} # rootのホームディレクトリは/rootとなってしまうため、root以外とする
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: /home/${FTP_USER_NAME}
    networks:
      default:
        ipv4_address: 192.168.1.5

networks:
  default:
    name: ddbj_ld
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
