version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms30g -Xmx30g"
      path.data: /usr/share/elasticsearch/data
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es01
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch2
      node.max_local_storage_nodes: 2
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9200}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9300}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/logs
    depends_on:
      - elasticsearch2
    restart: always

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: ${DDBJLD_ELASTICSEARCH_CONTAINER_NAME:-ddbjld_elasticsearch2}
    environment:
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: ${DDBJLD_ELASTICSEARCH_PASSWD:-ddbjld_elasticsearch_passwd}
      ES_JAVA_OPTS: "-Xms30g -Xmx30g"
      TAKE_FILE_OWNERSHIP: "true"
      node.name: es02
      path.data: /usr/share/elasticsearch/data
      node.max_local_storage_nodes: 2
      discovery.zen.ping.unicast.hosts: ddbjld_elasticsearch
      cluster.initial_master_nodes: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${DDBJLD_ELASTICSEARCH_PORT_HTTP:-9201}:9200
      - ${DDBJLD_ELASTICSEARCH_PORT_NODE:-9301}:9300
    user: ${UID:-1000}:${GID:-0}  # 1000:0 is elasticsearch container's default
    command: ["bash", "/usr/local/bin/entrypoint.elasticsearch.sh"]
    volumes:
      - ${PWD}/config/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/config/entrypoint.elasticsearch.sh:/usr/local/bin/entrypoint.elasticsearch.sh
      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/logs/elasticsearch:/usr/share/elasticsearch/log
    restart: always

  public_db:
    image: postgres:12.0
    container_name: ${DDBJLD_POSTGRESQL_CONTAINER_NAME:-ddbjld_public_db}
    ports:
      - 5432:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/public_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/psql/:/var/lib/public_db/data
    environment:
      POSTGRES_USER: ${PUBLIC_DB_USER}
      POSTGRES_PASSWORD: ${PUBLIC_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${PUBLIC_DB_INITDB_ARGS}
      POSTGRES_DB: ${PUBLIC_DB}
    restart: always

  jvar_db:
    image: postgres:12.0
    ports:
      - 5433:5432
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/jvar_db/init:/docker-entrypoint-initdb.d
      - ${PWD}/data/jvar_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${JVAR_DB_USER}
      POSTGRES_PASSWORD: ${JVAR_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${JVAR_DB_INITDB_ARGS}
      POSTGRES_DB: ${JVAR_DB}
    restart: always

  batch:
    build:
      context: ${PWD}/batch
    image: ddbj-batch/boot:0.0.1
    depends_on:
    - public_db
    - elasticsearch
    - elasticsearch2
    user: ${UID:-0}:${GID:-0}
    volumes:
    - ${PWD}/batch:/batch
    - /gpfs1/dpl0/ddbjshare/private/ddbj.nig.ac.jp/jga/metadata:/data/jga
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
      TARGET_DB: ${TARGET_DB}

  api:
    image: openjdk:11-slim
    depends_on:
      - public_db
    ports:
      - "8090:8080"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/entrypoint.api.sh:/usr/local/bin/entrypoint.api.sh
      - ${PWD}/api:/api
      - ${PWD}/data/file:/data
    command: ["bash", "/usr/local/bin/entrypoint.api.sh"]
    restart: always
    environment:
      ENV: ${ENV}
    extra_hosts:
      - "gw1:172.19.18.250"

  front:
    image: node:12.12.0
    volumes:
      - "./front:/front"
    ports:
      - "3000:3000"
    user: ${UID:-0}:${GID:-0}
    working_dir: /front
    command: [sh, -c, yarn install;yarn build;yarn run start]
    restart: always

networks:
  default:
    name: ddbj_ld
