# add username and password of postgres
# If you need exec in local, change hostname.
spring:
  datasource:
    url:  jdbc:postgresql://postgresql/ddbj
    username:
    password:
    driverClassName: org.postgresql.Driver

# If you need in development, change DEBUG or TRACE
logging:
  level:
    root: INFO

# If you need exec in local, change draXmlPath,jsonPath
# If you need to change the limit to insert at once, change maximumRecord
settings:
  bioProjectPath: /app/src/main/resources/bioproject/
  bioSamplePath: /app/src/main/resources/biosample/
  draXmlPath: /app/src/main/resources/xml/dra/
  jgaXmlPath: /app/src/main/resources/xml/jga/
  tsvPath: /app/src/main/resources/tsv/
  csvPath: /app/src/main/resources/csv/
  maximumRecord: 1000
  timeStampFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
  hostname: elasticsearch
  port: 9200
  scheme: http
