# add username and password of postgres
spring:
  datasource:
    url:  jdbc:postgresql://localhost/ddbj
    username:
    password:
    driverClassName: org.postgresql.Driver

# If you need in development, change DEBUG or TRACE
logging:
  level:
    root: INFO

settings:
  # add XML path
  xmlPath:
  # add JSON path
  jsonPath:
