# add username and password of postgres
# If you need exec in local, change hostname.
spring:
  datasource:
    url:  jdbc:postgresql://postgresql/ddbj
    username:
    password:
    driverClassName: org.postgresql.Driver

# If you need in development, change DEBUG or TRACE
logging:
  level:
    root: INFO

# If you need exec in local, change Path.
settings:
  xmlPath: /app/src/main/resources/xml/
  jsonPath: /app/src/main/resources/json/
